<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            margin: 0;
            padding: 0;
            background: #f9f9f9;
          }
          #content {
            max-width: 1000px;
            margin: 40px auto;
            background: #fff;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.05);
          }
          h1 {
            font-size: 24px;
            font-weight: 600;
            margin-bottom: 20px;
            color: #111;
          }
          p.expl {
            margin-bottom: 20px;
            line-height: 1.5;
            color: #666;
          }
          p.expl a {
            color: #0070f3;
            text-decoration: none;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th {
            text-align: left;
            padding: 15px;
            background: #f5f5f5;
            color: #444;
            font-weight: 600;
            border-bottom: 1px solid #eee;
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          td {
            padding: 15px;
            border-bottom: 1px solid #eee;
            font-size: 14px;
            color: #555;
          }
          tr:hover td {
            background: #fafafa;
          }
          a {
            color: #0070f3;
            text-decoration: none;
            transition: color 0.2s;
          }
          a:hover {
            color: #0056b3;
            text-decoration: underline;
          }
          .count {
            background: #0070f3;
            color: white;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 12px;
            margin-left: 10px;
            vertical-align: middle;
          }
        </style>
      </head>
      <body>
        <div id="content">
          <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
            <h1>XML Sitemap Index <span class="count"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> Sitemaps</span></h1>
            <p class="expl">
              This XML Sitemap Index is generated by Next.js to organize this blog's content.
            </p>
            <table id="sitemap" cellpadding="3">
              <thead>
                <tr>
                  <th width="75%">Sitemap URL</th>
                  <th width="25%">Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td>
                      <xsl:variable name="itemURL">
                        <xsl:value-of select="sitemap:loc"/>
                      </xsl:variable>
                      <a href="{$itemURL}">
                        <xsl:value-of select="sitemap:loc"/>
                      </a>
                    </td>
                    <td>
                      <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
          <xsl:if test="count(sitemap:urlset/sitemap:url) &gt; 0">
            <h1>XML Sitemap <span class="count"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> Posts</span></h1>
            <p class="expl">
              This XML Sitemap is generated by Next.js to allow search engines to discover this blog's content.
            </p>
            <table id="sitemap" cellpadding="3">
              <thead>
                <tr>
                  <th width="50%">URL</th>
                  <th width="30%">News Title</th>
                  <th width="20%">Publication Date</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td>
                      <xsl:variable name="itemURL">
                        <xsl:value-of select="sitemap:loc"/>
                      </xsl:variable>
                      <a href="{$itemURL}">
                        <xsl:value-of select="sitemap:loc"/>
                      </a>
                    </td>
                    <td>
                      <xsl:choose>
                        <xsl:when test="news:news/news:title">
                          <xsl:value-of select="news:news/news:title"/>
                        </xsl:when>
                        <xsl:otherwise>
                          <span style="color:#999; font-style:italic;">N/A</span>
                        </xsl:otherwise>
                      </xsl:choose>
                    </td>
                    <td>
                      <xsl:choose>
                        <xsl:when test="news:news/news:publication_date">
                          <xsl:value-of select="concat(substring(news:news/news:publication_date,0,11),concat(' ', substring(news:news/news:publication_date,12,5)))"/>
                        </xsl:when>
                        <xsl:when test="sitemap:lastmod">
                           <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
                        </xsl:when>
                        <xsl:otherwise>
                          <span style="color:#999;">-</span>
                        </xsl:otherwise>
                      </xsl:choose>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
